//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class forecast
    {
        public int forecast_id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public string image_url { get; set; }
        public string result { get; set; }
    
        public virtual stock stock { get; set; }
    }
}
