//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription_types
    {
        public subscription_types()
        {
            this.subscriptions = new HashSet<subscription>();
        }
    
        public int subscription_type_id { get; set; }
        public string subscription_type { get; set; }
        public decimal price { get; set; }
        public int days { get; set; }
        public int months { get; set; }
        public int years { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<subscription> subscriptions { get; set; }
    }
}
