//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_stocks
    {
        public int user_stock_id { get; set; }
        public int user_id { get; set; }
        public int stock_id { get; set; }
    
        public virtual stock stock { get; set; }
        public virtual user user { get; set; }
    }
}
