//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.subscriptions = new HashSet<subscription>();
            this.user_stocks = new HashSet<user_stocks>();
        }
    
        public int user_id { get; set; }
        public int role_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string avatar { get; set; }
    
        public virtual role role { get; set; }
        public virtual ICollection<subscription> subscriptions { get; set; }
        public virtual ICollection<user_stocks> user_stocks { get; set; }
    }
}
